// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aTC3q87SvYM316XzoAz9a2
// Component: oorXTprwULV9C_
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: Yh3OL_UqnMDQoH/component
import Button from "../../Button"; // plasmic-import: cDQxsDRfT9gIBv/component
import FathymFooter from "../../FathymFooter"; // plasmic-import: KWLt0Ypx6GRqq/component

import { useScreenVariants as useScreenVariants_2MnWPdLissBd6Z } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 2mnWPdLissBD6Z/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_new_iotensemble_com.module.css"; // plasmic-import: aTC3q87SvYM316XzoAz9a2/projectcss
import sty from "./PlasmicHomepageVariant2.module.css"; // plasmic-import: oorXTprwULV9C_/css

import AppleIcon from "./icons/PlasmicIcon__Apple"; // plasmic-import: 3B5pxrnVxk-ZUY/icon
import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: vmCK544ZPyk_gQ/icon
import socialFeedDashboardpngGlPgP0YKq9TQr1 from "./images/socialFeedDashboardpng.png"; // plasmic-import: glPgP0YKq9tQR1/picture
import gettingStartedTemplatepngFElbPuPfSiBCex from "./images/gettingStartedTemplatepng.png"; // plasmic-import: FElbPuPFSiBCex/picture
import homeRoutespng3R9PZd2LBqt0DDt from "./images/homeRoutespng3.png"; // plasmic-import: R9pZd2lBqt0dDT/picture
import processorDetailspng3PzqyezeN1WbDb from "./images/processorDetailspng.png"; // plasmic-import: 3pzqyezeN1WbDB/picture
import routes2PngDeEx17ShWbPdWz from "./images/routes2Png.png"; // plasmic-import: DeEX17SHWbPdWz/picture
import anotherSocialFeedShotpngJakhIiJXgw3YM from "./images/anotherSocialFeedShotpng.png"; // plasmic-import: jakhIi_jXGW3yM/picture
import microsoftTeamsImage4PngWfrGbE8Mq9KAkU from "./images/microsoftTeamsImage4Png.png"; // plasmic-import: WfrGbE8Mq9kAkU/picture

export type PlasmicHomepageVariant2__VariantMembers = {};

export type PlasmicHomepageVariant2__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepageVariant2__VariantsArgs;
export const PlasmicHomepageVariant2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicHomepageVariant2__ArgsType = {};
type ArgPropType = keyof PlasmicHomepageVariant2__ArgsType;
export const PlasmicHomepageVariant2__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepageVariant2__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  h1?: p.Flex<"h1">;
  svg?: p.Flex<"svg">;
  learnMore?: p.Flex<"a">;
  link?: p.Flex<"a">;
  ol?: p.Flex<"ol">;
  section?: p.Flex<"section">;
  foreground3?: p.Flex<"div">;
  fathymFooter?: p.Flex<typeof FathymFooter>;
};

export interface DefaultHomepageVariant2Props {
  className?: string;
}

function PlasmicHomepageVariant2__RenderFunc(props: {
  variants: PlasmicHomepageVariant2__VariantsArgs;
  args: PlasmicHomepageVariant2__ArgsType;
  overrides: PlasmicHomepageVariant2__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_2MnWPdLissBd6Z()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__ntDm1)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__jyY2)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__djAau)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__zPoNm)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__wXcPe)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__zRp65)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rmI7
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__r8WC
                          )}
                        >
                          <h1
                            data-plasmic-name={"h1"}
                            data-plasmic-override={overrides.h1}
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              projectcss.__wab_text,
                              sty.h1
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>
                                {"Deliver sites with the utmost"}
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#5856D6" }}
                              >
                                {" flexibility and speed."}
                              </span>
                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          </h1>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__s8O3G
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <h2
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h2,
                                    projectcss.__wab_text,
                                    sty.h2___65EYv
                                  )}
                                >
                                  <React.Fragment>
                                    <React.Fragment>
                                      {
                                        "Developers use Fathym to host, manage and deploy future-proof web projects and applications – "
                                      }
                                    </React.Fragment>
                                    <span
                                      className={
                                        "plasmic_default__all plasmic_default__span"
                                      }
                                      style={{
                                        fontWeight: 700,
                                        color: "#5856D6"
                                      }}
                                    >
                                      {"powered by Azure"}
                                    </span>
                                    <React.Fragment>
                                      {
                                        " – with the flexibility and speed the modern web demands.\n\n"
                                      }
                                    </React.Fragment>
                                  </React.Fragment>
                                </h2>
                              }
                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.columns__keDYp
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__o93Gr
                              )}
                            >
                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button__ugyIa
                                )}
                                color={
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? ("blue" as const)
                                    : ("blue" as const)
                                }
                                endIcon={
                                  <ChevronRightIcon
                                    data-plasmic-name={"svg"}
                                    data-plasmic-override={overrides.svg}
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg
                                    )}
                                    role={"img"}
                                  />
                                }
                                link={
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? ("/dashboard/create-project" as const)
                                    : ("/dashboard" as const)
                                }
                                showEndIcon={
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? true
                                    : true
                                }
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__muC0G
                                  )}
                                >
                                  {"Get Started for Free"}
                                </div>
                              </Button>
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column___7YE5K
                              )}
                            >
                              <a
                                data-plasmic-name={"learnMore"}
                                data-plasmic-override={overrides.learnMore}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.learnMore
                                )}
                                href={"/docs" as const}
                                target={"_blank" as const}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__v9Zpx
                                  )}
                                >
                                  {"Learn more >"}
                                </div>
                              </a>
                            </div>
                          </div>
                        </p.Stack>
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__m9V5Y)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___5XjEb)}
                        displayHeight={"491px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: socialFeedDashboardpngGlPgP0YKq9TQr1,
                          fullWidth: 1400,
                          fullHeight: 1486,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </p.Stack>
                </div>
              </p.Stack>
            </p.Stack>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__afCoJ)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___7Gbj3)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__wXAvq
                )}
              >
                {"Say goodbye to unwieldy frontend monoliths."}
              </h2>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tmYnZ
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      " \n\nFathym automates CI/CD builds, hosting and deployment so you can focus on building Jamstack sites or Single Page Applications with the JavaScript frameworks, Static Site Generators or no code builders you love. \n\nSteer clear of clunky frontend monoliths.\n\n"
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {
                      "Break your web project down into smaller and more manageable pieces for independent, flexible and scalable builds and deployments. "
                    }
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
            </p.Stack>
          </div>

          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__wPsyw)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oxN2J
                )}
              >
                {"TAKE THE FATHYM JOURNEY"}
              </div>
            </div>
          ) : null}

          <div className={classNames(projectcss.all, sty.freeBox__r8U14)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__tOqH9)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2___2Hd2C
                )}
              >
                {"1. Start with your code."}
              </h2>

              <div className={classNames(projectcss.all, sty.columns__fyZm)}>
                <div className={classNames(projectcss.all, sty.column__wltmC)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uyTAl
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "Getting started is as simple as connecting your GitHub repository. \n\n"
                        }
                      </React.Fragment>
                      {
                        <a
                          data-plasmic-name={"link"}
                          data-plasmic-override={overrides.link}
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link
                          )}
                          href={
                            "https://www.fathym.com/dashboard/create-project" as const
                          }
                          target={"_blank" as const}
                        >
                          {"Select an open-source recipe"}
                        </a>
                      }
                      <React.Fragment>
                        {
                          " from your favorite frameworks or static site generators see Fathym in action or bring in your own code."
                        }
                      </React.Fragment>
                    </React.Fragment>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__kiahA)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__cpi9A)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__p38Jb
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__oVhKs
                          )}
                        >
                          {"Your code."}
                        </h3>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dbLaq
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>
                              {
                                "Bring your sites and applications that you already have in"
                              }
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#5856D6" }}
                            >
                              {" "}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700, color: "#5856D6" }}
                            >
                              {"GitHub"}
                            </span>
                            <React.Fragment>{" or "}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700, color: "#5856D6" }}
                            >
                              {"NPM"}
                            </span>
                            <React.Fragment>{"."}</React.Fragment>
                          </React.Fragment>
                        </div>

                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__i7OGp
                          )}
                        >
                          {"Build and deploy."}
                        </h3>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8Pkcj
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>
                              {"Let us handle the "}
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700, color: "#5856D6" }}
                            >
                              {"automated build pipelines and deployments"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {" "}
                            </span>
                            <React.Fragment>
                              {
                                "behind the scenes so you can stick to the good stuff."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__dCc0)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__kn31X)}
                          displayHeight={"364px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: gettingStartedTemplatepngFElbPuPfSiBCex,
                            fullWidth: 1962,
                            fullHeight: 1544,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </p.Stack>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__wjz2Z)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__xkHHn)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__l4Sx2
                )}
              >
                {"2. Break it down."}
              </h2>

              {true ? (
                <div className={classNames(projectcss.all, sty.columns__xDqHr)}>
                  <div
                    className={classNames(projectcss.all, sty.column__z47ND)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9Guk4
                      )}
                    >
                      {
                        "Break website projects down into smaller apps with individual repositories and automated build pipelines for:  \n\n"
                      }
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7BiAn
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ol
                            data-plasmic-name={"ol"}
                            data-plasmic-override={overrides.ol}
                            className={classNames(
                              projectcss.all,
                              projectcss.ol,
                              sty.ol
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__klqcA
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>
                                  {"Smaller, more cohesive, decoupled "}
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700, color: "#5856D6" }}
                                >
                                  {"codebases."}
                                </span>
                                <React.Fragment>{""}</React.Fragment>
                              </React.Fragment>
                            </li>

                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__djKkf
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>
                                  {"Smaller, faster "}
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700, color: "#5856D6" }}
                                >
                                  {"builds."}
                                </span>
                                <React.Fragment>{""}</React.Fragment>
                              </React.Fragment>
                            </li>

                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__nUpdX
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>
                                  {"Simple testing, version control and "}
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700, color: "#5856D6" }}
                                >
                                  {"release management."}
                                </span>
                                <React.Fragment>{""}</React.Fragment>
                              </React.Fragment>
                            </li>

                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__qVqEz
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>
                                  {"Incremental upgrades and independent "}
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700, color: "#5856D6" }}
                                >
                                  {"deployments."}
                                </span>
                                <React.Fragment>{""}</React.Fragment>
                              </React.Fragment>
                            </li>

                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__bjFo4
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>
                                  {"Flexibility to fork and "}
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700, color: "#5856D6" }}
                                >
                                  {"re-use modular apps"}
                                </span>
                                <React.Fragment>
                                  {" for other projects."}
                                </React.Fragment>
                              </React.Fragment>
                            </li>
                          </ol>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              ) : null}

              <div className={classNames(projectcss.all, sty.columns__yFzws)}>
                <div className={classNames(projectcss.all, sty.column__mZibH)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___7El0L
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__w7PaK
                          )}
                        >
                          {"You're a composer."}
                        </h3>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pikFo
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "Build with the freedom to use different JavaScript frameworks, Static Site Generators or even no code builders on the one site. \n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700, color: "#000000" }}
                      >
                        {"Use the right framework for the right job. "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {" "}
                      </span>
                      <React.Fragment>
                        {
                          "\n\nFathym effortlessly brings your project’s apps together to compose one cohesive and seamless website or web app on your custom domain. "
                        }
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column___82Lum)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ygZvg)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: homeRoutespng3R9PZd2LBqt0DDt,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </p.Stack>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__pposC)}>
            <div className={classNames(projectcss.all, sty.freeBox___2KSHx)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__y7HbL
                )}
              >
                {"3. Deploy with confidence."}
              </h2>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dy2J3
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                  <React.Fragment>
                    <React.Fragment>{"The "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700, color: "#5856D6" }}
                    >
                      {"Fathym Global Edge Network"}
                    </span>
                    <React.Fragment>
                      {
                        " leverages Azure CDN to deliver your content and sites to the global points closest to your users. \n\nTake advantage of independent builds and deployments so you can work concurrently on your web project.\n\nUpdate to any version of your apps with version control, and easily rollback when things go awry without impacting your production site. \n\n"
                      }
                    </React.Fragment>
                  </React.Fragment>
                ) : (
                  <React.Fragment>
                    <React.Fragment>{"The "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700, color: "#5856D6" }}
                    >
                      {"Fathym Global Edge Network"}
                    </span>
                    <React.Fragment>
                      {
                        " leverages the Azure CDN to deliver your content and sites to the global points closest to your users. \n\nTake advantage of "
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#5856D6", fontWeight: 700 }}
                    >
                      {"independent builds and deployments"}
                    </span>
                    <React.Fragment>
                      {
                        " so you can work concurrently on your web project.\n\nUpdate to any version of your apps with version control, and easily rollback when things go awry without impacting your production site. \n\n"
                      }
                    </React.Fragment>
                  </React.Fragment>
                )}
              </div>

              <div className={classNames(projectcss.all, sty.columns__bipvh)}>
                <div className={classNames(projectcss.all, sty.column__iaCo7)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__zQRpL)}
                    displayHeight={"400px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: processorDetailspng3PzqyezeN1WbDb,
                      fullWidth: 1180,
                      fullHeight: 1026,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__mUqkH)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qdxB)}
                    displayHeight={"400px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"150%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: routes2PngDeEx17ShWbPdWz,
                      fullWidth: 624,
                      fullHeight: 626,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__iIhih)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__pY4Lz)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__qBqWw
                )}
              >
                {"4. Scale as you grow."}
              </h2>

              <div className={classNames(projectcss.all, sty.columns__pLfB7)}>
                <div className={classNames(projectcss.all, sty.column__jCaY3)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aMn6
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                      <React.Fragment>
                        <React.Fragment>
                          {"Get started for free in a \n"}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700, color: "#5856D6" }}
                        >
                          {"shared infrastructure environment"}
                        </span>
                        <React.Fragment>
                          {
                            " built to scale with you and your customer's needs.\n\nOutgrown Fathym's shared infrastructure?\n\nEmploy all the same great tools from your own "
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700, color: "#5856D6" }}
                        >
                          {"managed or private Azure clouds."}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    ) : (
                      <React.Fragment>
                        <React.Fragment>
                          {"Get started for free in a "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700, color: "#5856D6" }}
                        >
                          {"shared infrastructure environment"}
                        </span>
                        <React.Fragment>
                          {
                            " built to scale with you and your customer's needs.\n\nOutgrown Fathym's shared infrastructure?\n\nEmploy all the same great tools from your own "
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700, color: "#5856D6" }}
                        >
                          {"managed or private Azure clouds."}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    )}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__fLgbq)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lriTd
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "Take advantage of our simplified developer experience while scaling to your own Azure cloud with full access to your own infrastructure and the full range and power of Azure's extensive services.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700, color: "#5856D6" }}
                      >
                        {
                          "Build a future-proof tech stack from the get go without the complexity. "
                        }
                      </span>
                      <React.Fragment>{"\n\n\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700, color: "#5856D6" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
              </div>
            </p.Stack>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__gti7Z)}>
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__bqVw
              )}
            >
              {"Stay in sync with your team."}
            </h2>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__i9Th1
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "Collaborating and keeping updated with your teammate’s builds, pull requests and deploys has never been easier than through our"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {" interactive social feed"}
                </span>
                <React.Fragment>{".  \n\nFathym offers "}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"one consolidated workflow"}
                </span>
                <React.Fragment>
                  {
                    " for you to view and manage your web projects and their corresponding repositories and builds."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__bSZc4)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("274px" as const)
                  : ("527px" as const)
              }
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("407px" as const)
                  : ("750px" as const)
              }
              loading={"lazy" as const}
              src={{
                src: anotherSocialFeedShotpngJakhIiJXgw3YM,
                fullWidth: 2144,
                fullHeight: 1496,
                aspectRatio: undefined
              }}
            />
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__gFYl2)}>
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__taELl
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {"Leverage the power of Azure\n"}
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#5856D6" }}
                >
                  {"minus the complexity."}
                </span>
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </h2>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__j7Sl4
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "Fathym leverages Azure for the most advanced, enterprise-grade infrastructure and world class "
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"performance, reliability and security. "}
                </span>
                <React.Fragment>
                  {"\n\nControl who accesses your apps through out-of-the-box "}
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"authentication"}
                </span>
                <React.Fragment>{" and"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {" "}
                </span>
                <React.Fragment>{"\n"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"identity management."}
                </span>
                <React.Fragment>
                  {
                    "\n\nAs you scale and need the flexibility and full range of services that only the big cloud providers offer, we'll"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#5856D6" }}
                >
                  {" "}
                </span>
                <React.Fragment>{""}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#5856D6", fontWeight: 700 }}
                >
                  {
                    "automate best practice infrastructure in your own Azure environment."
                  }
                </span>
                <React.Fragment>{""}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {" "}
                </span>
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__igTmX)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("458px" as const)
                  : ("455px" as const)
              }
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("439px" as const)
                  : ("auto" as const)
              }
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage4PngWfrGbE8Mq9KAkU,
                fullWidth: 1348,
                fullHeight: 921,
                aspectRatio: undefined
              }}
            />
          </div>

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground3"}
              data-plasmic-override={overrides.foreground3}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__it26J)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__zMvMu)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__jhuqx
                    )}
                  >
                    {"Why deploy with Fathym?"}
                  </h2>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jNri
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "Fathym's powerful micro frontends allow work to be divided and conquered concurrently. Virtual developers handle the heavy lifting of the hosting and DevOps automation, saving you time and money. \n\nPlus, the freedom to use multiple frameworks, static site generators or no code builders on the one project!\n\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {
                        "Take advantage of Fathym's streamlined PaaS developer experience while future proofing your tech stack in the knowledge that you can scale to your own automated Azure cloud when ready."
                      }
                    </span>
                    <React.Fragment>{"\n"}</React.Fragment>
                  </React.Fragment>
                </div>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.columns__sUsPt)}>
                <div className={classNames(projectcss.all, sty.column__hEyDx)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__psFTa)}
                    color={"blue" as const}
                    link={"/dashboard" as const}
                  >
                    {"Get Started for Free"}
                  </Button>
                </div>
              </div>
            </p.Stack>
          </section>

          <FathymFooter
            data-plasmic-name={"fathymFooter"}
            data-plasmic-override={overrides.fathymFooter}
            className={classNames("__wab_instance", sty.fathymFooter)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "h1",
    "svg",
    "learnMore",
    "link",
    "ol",
    "section",
    "foreground3",
    "fathymFooter"
  ],
  navbar: ["navbar"],
  h1: ["h1"],
  svg: ["svg"],
  learnMore: ["learnMore"],
  link: ["link"],
  ol: ["ol"],
  section: ["section", "foreground3"],
  foreground3: ["foreground3"],
  fathymFooter: ["fathymFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  h1: "h1";
  svg: "svg";
  learnMore: "a";
  link: "a";
  ol: "ol";
  section: "section";
  foreground3: "div";
  fathymFooter: typeof FathymFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepageVariant2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepageVariant2__VariantsArgs;
    args?: PlasmicHomepageVariant2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepageVariant2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepageVariant2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepageVariant2__ArgProps,
          internalVariantPropNames: PlasmicHomepageVariant2__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepageVariant2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepageVariant2";
  } else {
    func.displayName = `PlasmicHomepageVariant2.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepageVariant2 = Object.assign(
  // Top-level PlasmicHomepageVariant2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    h1: makeNodeComponent("h1"),
    svg: makeNodeComponent("svg"),
    learnMore: makeNodeComponent("learnMore"),
    link: makeNodeComponent("link"),
    ol: makeNodeComponent("ol"),
    section: makeNodeComponent("section"),
    foreground3: makeNodeComponent("foreground3"),
    fathymFooter: makeNodeComponent("fathymFooter"),

    // Metadata about props expected for PlasmicHomepageVariant2
    internalVariantProps: PlasmicHomepageVariant2__VariantProps,
    internalArgProps: PlasmicHomepageVariant2__ArgProps
  }
);

export default PlasmicHomepageVariant2;
/* prettier-ignore-end */
