// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aTC3q87SvYM316XzoAz9a2
// Component: Ct6Rh1SZhEvlvP
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: Yh3OL_UqnMDQoH/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import YouTube from "@plasmicpkgs/react-youtube"; // plasmic-import: CHO21V9uYw/codeComponent
import Button from "../../Button"; // plasmic-import: cDQxsDRfT9gIBv/component
import Section from "../../Section"; // plasmic-import: sdnKnX5vOOj8jX/component
import ValueProp from "../../ValueProp"; // plasmic-import: TgzPqT9E_wfNat/component
import Banner from "../../Banner"; // plasmic-import: wOD-nHMwc8Vx9X/component
import PriceCard from "../../PriceCard"; // plasmic-import: Dm_4qJAK1AxCbj/component
import FathymFooter from "../../FathymFooter"; // plasmic-import: KWLt0Ypx6GRqq/component

import { useScreenVariants as useScreenVariants_2MnWPdLissBd6Z } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 2mnWPdLissBD6Z/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_new_iotensemble_com.module.css"; // plasmic-import: aTC3q87SvYM316XzoAz9a2/projectcss
import sty from "./PlasmicLandingPagesReact2.module.css"; // plasmic-import: Ct6Rh1SZhEvlvP/css

import AppleIcon from "./icons/PlasmicIcon__Apple"; // plasmic-import: 3B5pxrnVxk-ZUY/icon
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: hDULe3Rv0s35IQ/icon
import HammerIcon from "./icons/PlasmicIcon__Hammer"; // plasmic-import: qrqCHWq7Cs5_QA/icon
import TargetIcon from "./icons/PlasmicIcon__Target"; // plasmic-import: XTkp8IcnsrPIhU/icon
import FastIcon from "./icons/PlasmicIcon__Fast"; // plasmic-import: z9lFrPVzngCt3_/icon
import StrongIcon from "./icons/PlasmicIcon__Strong"; // plasmic-import: TITdVVbg6DA9uE/icon

export type PlasmicLandingPagesReact2__VariantMembers = {};

export type PlasmicLandingPagesReact2__VariantsArgs = {};
type VariantPropType = keyof PlasmicLandingPagesReact2__VariantsArgs;
export const PlasmicLandingPagesReact2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLandingPagesReact2__ArgsType = {};
type ArgPropType = keyof PlasmicLandingPagesReact2__ArgsType;
export const PlasmicLandingPagesReact2__ArgProps = new Array<ArgPropType>();

export type PlasmicLandingPagesReact2__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  foreground?: p.Flex<"div">;
  youTube?: p.Flex<typeof YouTube>;
  foreground2?: p.Flex<"div">;
  valuePropsSection?: p.Flex<typeof Section>;
  banner?: p.Flex<typeof Banner>;
  section?: p.Flex<"section">;
  foreground3?: p.Flex<"div">;
  fathymFooter?: p.Flex<typeof FathymFooter>;
};

export interface DefaultLandingPagesReact2Props {
  className?: string;
}

function PlasmicLandingPagesReact2__RenderFunc(props: {
  variants: PlasmicLandingPagesReact2__VariantsArgs;
  args: PlasmicLandingPagesReact2__ArgsType;
  overrides: PlasmicLandingPagesReact2__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_2MnWPdLissBd6Z()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__zc5E1)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground"}
              data-plasmic-override={overrides.foreground}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground)}
            >
              <Reveal
                className={classNames("__wab_instance", sty.reveal__m9Hku)}
                triggerOnce={false}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___16Yix
                  )}
                >
                  {"React Deployments\nwith Fathym"}
                </div>
              </Reveal>

              <Reveal
                className={classNames("__wab_instance", sty.reveal__b5Aqw)}
                triggerOnce={false}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6BBbj
                  )}
                >
                  {
                    "Create, build, and deploy your next JAMStack app with React on Fathym"
                  }
                </div>
              </Reveal>
            </p.Stack>

            <Reveal
              className={classNames("__wab_instance", sty.reveal__rijMr)}
              effect={"bounce" as const}
              triggerOnce={false}
            >
              <YouTube
                data-plasmic-name={"youTube"}
                data-plasmic-override={overrides.youTube}
                className={classNames("__wab_instance", sty.youTube)}
                videoId={"afqLbfqUF5Q" as const}
              />
            </Reveal>

            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.columns__fl08S)}>
                <div className={classNames(projectcss.all, sty.column__kdMyn)}>
                  <Button
                    className={classNames("__wab_instance", sty.button___5Un6)}
                    color={"blue" as const}
                    link={"/dashboard/create-project/recipe/react" as const}
                  >
                    {"Get Started for Free"}
                  </Button>
                </div>

                <div className={classNames(projectcss.all, sty.column__r8Np7)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__h3HeG
                    )}
                    href={"/docs/guides/deploying/frameworks/react" as const}
                  >
                    {"Learn more >"}
                  </a>
                </div>
              </div>
            </p.Stack>

            <Section
              data-plasmic-name={"valuePropsSection"}
              data-plasmic-override={overrides.valuePropsSection}
              className={classNames("__wab_instance", sty.valuePropsSection)}
            >
              <Reveal
                className={classNames("__wab_instance", sty.reveal___9W9Ij)}
                direction={"down" as const}
                triggerOnce={false}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__owsAf)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xiTkr)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2___4GRro
                      )}
                    >
                      {"See how React Compares"}
                    </h2>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rVtZb
                    )}
                  >
                    {
                      "Looking for the right framework for your next Jamstack example, tutorial or project?  Deploy React alongside any number of additional frameworks, get a feel for the development experience, and see how they perform.  Host your React app free with Fathym's micro frontend framework."
                    }
                  </div>
                </p.Stack>
              </Reveal>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kO3Mc)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nuOoY)}
                >
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal___6K6Go)}
                    direction={"up" as const}
                    triggerOnce={false}
                  >
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp__eyqnb
                      )}
                      description={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fZkXi
                            )}
                          >
                            {
                              "Learn one way to build applications with Angular and reuse your code and abilities to build apps for any deployment target. Deploy your Angular app now."
                            }
                          </div>

                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__hHlGr
                            )}
                            href={"/angular" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__nn1Ob
                              )}
                            >
                              {"Angular Deployments >"}
                            </div>
                          </a>

                          {true ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__orvOt
                              )}
                              link={"/angular" as const}
                            >
                              {null}
                            </Button>
                          ) : null}
                        </React.Fragment>
                      }
                      flatIcon={true}
                      icon={
                        <CheckIcon
                          className={classNames(projectcss.all, sty.svg__s7L6)}
                          role={"img"}
                        />
                      }
                      title={"React vs Angular"}
                    />
                  </Reveal>

                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__swsEv)}
                    direction={"up" as const}
                    triggerOnce={false}
                  >
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp__zTwXv
                      )}
                      description={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kR6Kg
                            )}
                          >
                            {
                              "The progressive javascript framework.  Already know HTML, CSS and JavaScript? Read the guide and start deploying VueJS apps in no time!               \n"
                            }
                          </div>

                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__fZuj
                            )}
                            href={"/vue" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uaYf3
                              )}
                            >
                              {"Vue Deployments >"}
                            </div>
                          </a>

                          {true ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__jc7Vf
                              )}
                              link={"/vue" as const}
                            >
                              {null}
                            </Button>
                          ) : null}
                        </React.Fragment>
                      }
                      flatIcon={true}
                      icon={
                        <CheckIcon
                          className={classNames(projectcss.all, sty.svg__mes97)}
                          role={"img"}
                        />
                      }
                      title={"React vs VueJS"}
                    />
                  </Reveal>

                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__w9LN2)}
                    direction={"up" as const}
                    triggerOnce={false}
                  >
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp__pwBiq
                      )}
                      description={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xZ71H
                            )}
                          >
                            {
                              "Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app."
                            }
                          </div>

                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__a8CcV
                            )}
                            href={"/svelte-deployment" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___0HiJw
                              )}
                            >
                              {"Svelte Deployments >"}
                            </div>
                          </a>

                          {true ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__tcixz
                              )}
                              link={"/svelte-deployment" as const}
                            >
                              {null}
                            </Button>
                          ) : null}
                        </React.Fragment>
                      }
                      flatIcon={true}
                      icon={
                        <CheckIcon
                          className={classNames(projectcss.all, sty.svg__z2U5X)}
                          role={"img"}
                        />
                      }
                      title={"React vs Svelte"}
                    />
                  </Reveal>
                </p.Stack>
              </p.Stack>
            </Section>

            <Banner
              data-plasmic-name={"banner"}
              data-plasmic-override={overrides.banner}
              className={classNames("__wab_instance", sty.banner)}
              left={
                <React.Fragment>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zIm
                    )}
                  >
                    {"React Example Tutorial"}
                  </div>

                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__r7L3)}
                    direction={"right" as const}
                    triggerOnce={false}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gd6QH
                      )}
                    >
                      {"Do it Yourself"}
                    </div>
                  </Reveal>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ciVwm
                    )}
                  >
                    {
                      "Get started now and deploy your React app to production following the simple deployment guide. Have your React micro frontend hosted on your domain in minutes."
                    }
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.columns__jGQr)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__fEaxU)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__tBfge
                        )}
                        color={"blue" as const}
                        link={"/dashboard/create-project/recipe/react" as const}
                      >
                        {"Get Started for Free"}
                      </Button>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__zypuv)}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__txxc5
                        )}
                        href={
                          "/docs/guides/deploying/frameworks/react" as const
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___5J6Bk
                          )}
                        >
                          {"Read Documentation >"}
                        </div>
                      </a>

                      {true ? (
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__t41Vy
                          )}
                          link={
                            "/docs/guides/deploying/frameworks/react" as const
                          }
                        >
                          {null}
                        </Button>
                      ) : null}
                    </div>
                  </div>
                </React.Fragment>
              }
            />
          </p.Stack>

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground3"}
              data-plasmic-override={overrides.foreground3}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ijr5P)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__roxUa)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__hbbek)}
                    direction={"right" as const}
                    triggerOnce={false}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__fJyu2
                      )}
                    >
                      {"Why deploy React?"}
                    </h2>
                  </Reveal>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wvX13
                  )}
                >
                  {
                    "A JavaScript library for building user interfaces.\n\nReact makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.\n\nBuild encapsulated components that manage their own state, then compose them to make complex UIs.\n\nSince component logic is written in JavaScript instead of templates, you can easily pass rich data through your app and keep state out of the DOM."
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bNfZ)}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns___8ZcTw)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__pYhbE)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__qn5Zy
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__usSe
                            )}
                          >
                            {
                              "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                            }
                          </div>
                        }
                        icon={
                          <HammerIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__r4Rkl
                            )}
                            role={"img"}
                          />
                        }
                        title={"Harder"}
                        vertical={true}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column___5E6G)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp___0JBZg
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yeqPe
                            )}
                          >
                            {
                              "Consequat scelerisque a eros taciti nisl a sodales."
                            }
                          </div>
                        }
                        icon={
                          <TargetIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__s9Gxl
                            )}
                            role={"img"}
                          />
                        }
                        title={"Better"}
                        vertical={true}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__bi11)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp___3XgyD
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__c1Z4W
                            )}
                          >
                            {
                              "Varius ad malesuada ullamcorper cursus scelerisque a a."
                            }
                          </div>
                        }
                        icon={
                          <FastIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mDquQ
                            )}
                            role={"img"}
                          />
                        }
                        title={"Faster"}
                        vertical={true}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__lm3Us)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__z7XP
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mIJ
                            )}
                          >
                            {
                              "Ut eu nam nostra taciti congue adipiscing curabitur."
                            }
                          </div>
                        }
                        icon={
                          <StrongIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wvqs
                            )}
                            role={"img"}
                          />
                        }
                        title={"Stronger"}
                        vertical={true}
                      />
                    </div>
                  </p.Stack>
                ) : null}
              </p.Stack>

              <div className={classNames(projectcss.all, sty.columns__azQDw)}>
                <div className={classNames(projectcss.all, sty.column__tyl2Q)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__zms4X)}
                    color={"blue" as const}
                    link={"/dashboard/create-project/recipe/react" as const}
                  >
                    {"Get Started for Free"}
                  </Button>
                </div>

                <div className={classNames(projectcss.all, sty.column__tMvRt)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___2M9V
                    )}
                    href={"/docs/guides/deploying/frameworks/react" as const}
                  >
                    {"Learn more >"}
                  </a>
                </div>
              </div>
            </p.Stack>
          </section>

          {true ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__o0Pcr)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qwnmQ)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__pv6Pa)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zMsE)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w04NA
                      )}
                    >
                      {"Pricing plans"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yK15I
                    )}
                  >
                    {
                      "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__uWeb)}
                >
                  <PriceCard
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__sZq9M
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__jnmRa
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__nQpG
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__muGj5
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___9Y7H6
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"0"}
                  />

                  <PriceCard
                    action={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9LgX
                        )}
                      >
                        {"Buy Pro"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__z3Rc4
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__tdV7L
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__wIrLa
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__yuEoS
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vkSq5
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__x6Xux
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__juIua
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"8"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wjNfa
                        )}
                      >
                        {"Pro"}
                      </div>
                    }
                  />

                  <PriceCard
                    action={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eOcQt
                        )}
                      >
                        {"Buy Team"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__rnjUm
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__nRwc4
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__og682
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__vd8AV
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__qK5Q
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__bXfxm
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__quXx
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__ipej
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__d4A1
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"16"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__koa3B
                        )}
                      >
                        {"Team"}
                      </div>
                    }
                  />

                  <PriceCard
                    action={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__z2M8A
                        )}
                      >
                        {"Contact us"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__d1HJd
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__dErly
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__tdRdd
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__xo6Lk
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__mwyai
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__kx9Lm
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__egZXo
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___0EluE
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vl7Ly
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"?"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ldzv2
                        )}
                      >
                        {"Enterprise"}
                      </div>
                    }
                    primary={true}
                  />
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}

          <FathymFooter
            data-plasmic-name={"fathymFooter"}
            data-plasmic-override={overrides.fathymFooter}
            className={classNames("__wab_instance", sty.fathymFooter)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "foreground",
    "youTube",
    "foreground2",
    "valuePropsSection",
    "banner",
    "section",
    "foreground3",
    "fathymFooter"
  ],
  navbar: ["navbar"],
  foreground: ["foreground"],
  youTube: ["youTube"],
  foreground2: ["foreground2"],
  valuePropsSection: ["valuePropsSection"],
  banner: ["banner"],
  section: ["section", "foreground3"],
  foreground3: ["foreground3"],
  fathymFooter: ["fathymFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  foreground: "div";
  youTube: typeof YouTube;
  foreground2: "div";
  valuePropsSection: typeof Section;
  banner: typeof Banner;
  section: "section";
  foreground3: "div";
  fathymFooter: typeof FathymFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLandingPagesReact2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLandingPagesReact2__VariantsArgs;
    args?: PlasmicLandingPagesReact2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLandingPagesReact2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLandingPagesReact2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLandingPagesReact2__ArgProps,
          internalVariantPropNames: PlasmicLandingPagesReact2__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicLandingPagesReact2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLandingPagesReact2";
  } else {
    func.displayName = `PlasmicLandingPagesReact2.${nodeName}`;
  }
  return func;
}

export const PlasmicLandingPagesReact2 = Object.assign(
  // Top-level PlasmicLandingPagesReact2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    foreground: makeNodeComponent("foreground"),
    youTube: makeNodeComponent("youTube"),
    foreground2: makeNodeComponent("foreground2"),
    valuePropsSection: makeNodeComponent("valuePropsSection"),
    banner: makeNodeComponent("banner"),
    section: makeNodeComponent("section"),
    foreground3: makeNodeComponent("foreground3"),
    fathymFooter: makeNodeComponent("fathymFooter"),

    // Metadata about props expected for PlasmicLandingPagesReact2
    internalVariantProps: PlasmicLandingPagesReact2__VariantProps,
    internalArgProps: PlasmicLandingPagesReact2__ArgProps
  }
);

export default PlasmicLandingPagesReact2;
/* prettier-ignore-end */
