// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aTC3q87SvYM316XzoAz9a2
// Component: oI9EG3FGXR8uY6
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: Yh3OL_UqnMDQoH/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import YouTube from "@plasmicpkgs/react-youtube"; // plasmic-import: CHO21V9uYw/codeComponent
import Button from "../../Button"; // plasmic-import: cDQxsDRfT9gIBv/component
import Section from "../../Section"; // plasmic-import: sdnKnX5vOOj8jX/component
import ValueProp from "../../ValueProp"; // plasmic-import: TgzPqT9E_wfNat/component
import Banner from "../../Banner"; // plasmic-import: wOD-nHMwc8Vx9X/component
import PriceCard from "../../PriceCard"; // plasmic-import: Dm_4qJAK1AxCbj/component
import FathymFooter from "../../FathymFooter"; // plasmic-import: KWLt0Ypx6GRqq/component

import { useScreenVariants as useScreenVariants_2MnWPdLissBd6Z } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 2mnWPdLissBD6Z/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_new_iotensemble_com.module.css"; // plasmic-import: aTC3q87SvYM316XzoAz9a2/projectcss
import sty from "./PlasmicLandingPagesAngular2Test.module.css"; // plasmic-import: oI9EG3FGXR8uY6/css

import AppleIcon from "./icons/PlasmicIcon__Apple"; // plasmic-import: 3B5pxrnVxk-ZUY/icon
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: hDULe3Rv0s35IQ/icon
import HammerIcon from "./icons/PlasmicIcon__Hammer"; // plasmic-import: qrqCHWq7Cs5_QA/icon
import TargetIcon from "./icons/PlasmicIcon__Target"; // plasmic-import: XTkp8IcnsrPIhU/icon
import FastIcon from "./icons/PlasmicIcon__Fast"; // plasmic-import: z9lFrPVzngCt3_/icon
import StrongIcon from "./icons/PlasmicIcon__Strong"; // plasmic-import: TITdVVbg6DA9uE/icon

export type PlasmicLandingPagesAngular2Test__VariantMembers = {};

export type PlasmicLandingPagesAngular2Test__VariantsArgs = {};
type VariantPropType = keyof PlasmicLandingPagesAngular2Test__VariantsArgs;
export const PlasmicLandingPagesAngular2Test__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLandingPagesAngular2Test__ArgsType = {};
type ArgPropType = keyof PlasmicLandingPagesAngular2Test__ArgsType;
export const PlasmicLandingPagesAngular2Test__ArgProps =
  new Array<ArgPropType>();

export type PlasmicLandingPagesAngular2Test__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  foreground?: p.Flex<"div">;
  youTube?: p.Flex<typeof YouTube>;
  foreground2?: p.Flex<"div">;
  valuePropsSection?: p.Flex<typeof Section>;
  react?: p.Flex<"a">;
  vue?: p.Flex<"a">;
  svelte?: p.Flex<"a">;
  banner?: p.Flex<typeof Banner>;
  section?: p.Flex<"section">;
  foreground3?: p.Flex<"div">;
  fathymFooter?: p.Flex<typeof FathymFooter>;
};

export interface DefaultLandingPagesAngular2TestProps {
  className?: string;
}

function PlasmicLandingPagesAngular2Test__RenderFunc(props: {
  variants: PlasmicLandingPagesAngular2Test__VariantsArgs;
  args: PlasmicLandingPagesAngular2Test__ArgsType;
  overrides: PlasmicLandingPagesAngular2Test__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_2MnWPdLissBd6Z()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          {true ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__tqduC)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"foreground"}
                data-plasmic-override={overrides.foreground}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground)}
              >
                <Reveal
                  className={classNames("__wab_instance", sty.reveal___8Qx28)}
                  triggerOnce={false}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1X0Y1
                    )}
                  >
                    {"Angular Deployments\nwith Fathym"}
                  </div>
                </Reveal>

                <Reveal
                  className={classNames("__wab_instance", sty.reveal__sKvSi)}
                  triggerOnce={false}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nb5OS
                    )}
                  >
                    {
                      "Create, build, and deploy your next Angular app with Fathym"
                    }
                  </div>
                </Reveal>
              </p.Stack>

              <Reveal
                className={classNames("__wab_instance", sty.reveal__kx0DB)}
                effect={"bounce" as const}
                triggerOnce={false}
              >
                <YouTube
                  data-plasmic-name={"youTube"}
                  data-plasmic-override={overrides.youTube}
                  className={classNames("__wab_instance", sty.youTube)}
                  videoId={"FEWQr9RQ1Us" as const}
                />
              </Reveal>

              <p.Stack
                as={"div"}
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <div
                  className={classNames(projectcss.all, sty.columns___2WsSb)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__qjixL)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__wyz59
                      )}
                      color={"blue" as const}
                      link={"/dashboard/create-project/recipe/angular" as const}
                    >
                      {"Get Started for Free"}
                    </Button>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__ctoJz)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__rtpaf
                      )}
                      href={
                        "/docs/guides/deploying/frameworks/angular" as const
                      }
                    >
                      {"Learn more >"}
                    </a>
                  </div>
                </div>
              </p.Stack>

              <Section
                data-plasmic-name={"valuePropsSection"}
                data-plasmic-override={overrides.valuePropsSection}
                className={classNames("__wab_instance", sty.valuePropsSection)}
              >
                <Reveal
                  className={classNames("__wab_instance", sty.reveal___95Pt9)}
                  direction={"down" as const}
                  triggerOnce={true}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___5NhiP)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bg1Wq)}
                    >
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal__g45On
                        )}
                        direction={"down" as const}
                        triggerOnce={false}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            sty.h2__efjkk
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___6EW8
                            )}
                          >
                            {"See how Angular Compares"}
                          </div>
                        </h2>
                      </Reveal>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2FTk1
                      )}
                    >
                      {
                        "Looking for the right framework for your next JAMStack example, tutorial or project?  Deploy Angular alongside any number of additional frameworks, get a feel for the development experience, and see how they perform.  Deploy your Angular app free with Fathym's micro frontend framework."
                      }
                    </div>
                  </p.Stack>
                </Reveal>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__kO3Mc)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nuOoY)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal__lxIy9
                        )}
                        direction={"up" as const}
                        triggerOnce={false}
                      >
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___64Vw0
                          )}
                          description={
                            <React.Fragment>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___3GHLj
                                )}
                              >
                                {
                                  "React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components."
                                }
                              </div>

                              <a
                                data-plasmic-name={"react"}
                                data-plasmic-override={overrides.react}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.react
                                )}
                                href={"https://www.fathym.com/react/" as const}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___55WFh
                                  )}
                                >
                                  {"React Deployments >"}
                                </div>
                              </a>

                              {true ? (
                                <Button
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button__orvOt
                                  )}
                                  link={"/react" as const}
                                >
                                  {null}
                                </Button>
                              ) : null}
                            </React.Fragment>
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___82LpM
                              )}
                              role={"img"}
                            />
                          }
                          title={"Angular vs React"}
                        />
                      </Reveal>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal__kMqq
                        )}
                        direction={"up" as const}
                        triggerOnce={false}
                      >
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__gTmV
                          )}
                          description={
                            <React.Fragment>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___8Vyc7
                                )}
                              >
                                {
                                  "The progressive javascript framework.  Already know HTML, CSS and JavaScript? Read the guide and start deploying VueJS apps in no time!               \n"
                                }
                              </div>

                              <a
                                data-plasmic-name={"vue"}
                                data-plasmic-override={overrides.vue}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.vue
                                )}
                                href={"https://www.fathym.com/vue/" as const}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___2InBy
                                  )}
                                >
                                  {"Vue Deployments >"}
                                </div>
                              </a>

                              {true ? (
                                <Button
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button__jc7Vf
                                  )}
                                  link={"/vue" as const}
                                >
                                  {null}
                                </Button>
                              ) : null}
                            </React.Fragment>
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___0PDvQ
                              )}
                              role={"img"}
                            />
                          }
                          title={"Angular vs VueJS"}
                        />
                      </Reveal>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal__fH87S
                        )}
                        direction={"up" as const}
                        triggerOnce={false}
                      >
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__hdfhc
                          )}
                          description={
                            <React.Fragment>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___1Jsd5
                                )}
                              >
                                {
                                  "Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app."
                                }
                              </div>

                              <a
                                data-plasmic-name={"svelte"}
                                data-plasmic-override={overrides.svelte}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.svelte
                                )}
                                href={
                                  "https://www.fathym.com/svelte-deployment/" as const
                                }
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__sOugM
                                  )}
                                >
                                  {"Svelte Deployments >"}
                                </div>
                              </a>

                              {true ? (
                                <Button
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button__tcixz
                                  )}
                                  link={"/svelte-deployment" as const}
                                >
                                  {null}
                                </Button>
                              ) : null}
                            </React.Fragment>
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__hkWff
                              )}
                              role={"img"}
                            />
                          }
                          title={"Angular vs Svelte"}
                        />
                      </Reveal>
                    ) : null}
                  </p.Stack>
                </p.Stack>
              </Section>

              <Banner
                data-plasmic-name={"banner"}
                data-plasmic-override={overrides.banner}
                className={classNames("__wab_instance", sty.banner)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kkN3L
                      )}
                    >
                      {"Angular Example Tutorial"}
                    </div>

                    <Reveal
                      className={classNames("__wab_instance", sty.reveal__wnMn)}
                      direction={"right" as const}
                      triggerOnce={false}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__f4WWq
                        )}
                      >
                        {"Do it Yourself"}
                      </div>
                    </Reveal>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ciVwm
                      )}
                    >
                      {
                        "Get started now and deploy your Angular app to production following the simple deployment guide. Have your Angular micro frontend hosted on your domain in minutes."
                      }
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.columns__eNf1S)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___8URFu
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__b1V5L
                          )}
                          color={"blue" as const}
                          link={
                            "/dashboard/create-project/recipe/angular" as const
                          }
                        >
                          {"Get Started for Free"}
                        </Button>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__rdhWw
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link__xKbY
                          )}
                          href={
                            "/docs/guides/deploying/frameworks/angular" as const
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__uNsew
                            )}
                          >
                            {"Read Documentation >"}
                          </div>
                        </a>

                        {true ? (
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__hQJos
                            )}
                            link={
                              "/docs/guides/deploying/frameworks/angular" as const
                            }
                          >
                            {null}
                          </Button>
                        ) : null}
                      </div>
                    </div>
                  </React.Fragment>
                }
              />
            </p.Stack>
          ) : null}

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground3"}
              data-plasmic-override={overrides.foreground3}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__pa4WF)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__qXze)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__w1ZY)}
                    direction={"right" as const}
                    triggerOnce={false}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__fw6Wv
                      )}
                    >
                      {"Why deploy Angular?"}
                    </h2>
                  </Reveal>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oyy16
                  )}
                >
                  {
                    "The modern web developers platform.\n\nLearn one way to build applications with Angular and reuse your code and abilities to build apps for any deployment target. For web, mobile web, native mobile and native desktop.\n\nAchieve the maximum speed possible on the Web Platform today, and take it further, via Web Workers and server-side rendering.\n\nAngular puts you in control over scalability. Meet huge data requirements by building data models on RxJS, Immutable.js or another push-model.\n\nBuild features quickly with simple, declarative templates. Extend the template language with your own components and use a wide array of existing components. Get immediate Angular-specific help and feedback with nearly every IDE and editor. All this comes together so you can focus on building amazing apps rather than trying to make the code work."
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___4HWd1)}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__kuceE)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__wbuUm)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp___3HQng
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bVkm2
                            )}
                          >
                            {
                              "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                            }
                          </div>
                        }
                        icon={
                          <HammerIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wvD94
                            )}
                            role={"img"}
                          />
                        }
                        title={"Harder"}
                        vertical={true}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__khwwq)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__cifMk
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___2B7Y5
                            )}
                          >
                            {
                              "Consequat scelerisque a eros taciti nisl a sodales."
                            }
                          </div>
                        }
                        icon={
                          <TargetIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___75Qud
                            )}
                            role={"img"}
                          />
                        }
                        title={"Better"}
                        vertical={true}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__bvI8Z)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp___8U6Mu
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___6VtM
                            )}
                          >
                            {
                              "Varius ad malesuada ullamcorper cursus scelerisque a a."
                            }
                          </div>
                        }
                        icon={
                          <FastIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__yxgyh
                            )}
                            role={"img"}
                          />
                        }
                        title={"Faster"}
                        vertical={true}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__hMRz)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__zk00U
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__adTom
                            )}
                          >
                            {
                              "Ut eu nam nostra taciti congue adipiscing curabitur."
                            }
                          </div>
                        }
                        icon={
                          <StrongIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kv1B
                            )}
                            role={"img"}
                          />
                        }
                        title={"Stronger"}
                        vertical={true}
                      />
                    </div>
                  </p.Stack>
                ) : null}
              </p.Stack>

              <div className={classNames(projectcss.all, sty.columns__ooSdo)}>
                <div className={classNames(projectcss.all, sty.column__oUWa6)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__fhIk)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__qPza3
                      )}
                      color={"blue" as const}
                      link={"/dashboard/create-project/recipe/angular" as const}
                    >
                      {"Get Started for Free"}
                    </Button>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__ki6Hj
                      )}
                      href={
                        "/docs/guides/deploying/frameworks/angular" as const
                      }
                    >
                      {"Learn more >"}
                    </a>
                  </div>
                </div>

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.column__oTiq9)}
                  />
                ) : null}
              </div>
            </p.Stack>
          </section>

          {true ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__p4Ap0)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bC8)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__sGZn)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__h75Lh)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iJkpT
                      )}
                    >
                      {"Pricing plans"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4Sjmf
                    )}
                  >
                    {
                      "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___8ZR42)}
                >
                  <PriceCard
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__sAp1
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__eWej
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xzkoU
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__gnokw
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__msOtQ
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"0"}
                  />

                  <PriceCard
                    action={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gh91P
                        )}
                      >
                        {"Buy Pro"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__vklSe
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__eWoCx
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___5CAot
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__ei9F8
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__fh5Mm
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__dTtgk
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__bwZVn
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"8"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2HO7G
                        )}
                      >
                        {"Pro"}
                      </div>
                    }
                  />

                  <PriceCard
                    action={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qflAm
                        )}
                      >
                        {"Buy Team"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__es5GN
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___0BShO
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___9IbGx
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__gs9On
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__v3AUi
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__bwxTo
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__pEOvb
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__qaKSn
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__w40Lj
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"16"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tvIU
                        )}
                      >
                        {"Team"}
                      </div>
                    }
                  />

                  <PriceCard
                    action={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bK5Pq
                        )}
                      >
                        {"Contact us"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__pf4Bb
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__uq0Cy
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__y8TFc
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__tmobF
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__lrLqr
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__aoQ61
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__kWdQ4
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___5VoB
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__dFuWd
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"?"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kdhFf
                        )}
                      >
                        {"Enterprise"}
                      </div>
                    }
                    primary={true}
                  />
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}

          <FathymFooter
            data-plasmic-name={"fathymFooter"}
            data-plasmic-override={overrides.fathymFooter}
            className={classNames("__wab_instance", sty.fathymFooter)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "foreground",
    "youTube",
    "foreground2",
    "valuePropsSection",
    "react",
    "vue",
    "svelte",
    "banner",
    "section",
    "foreground3",
    "fathymFooter"
  ],
  navbar: ["navbar"],
  foreground: ["foreground"],
  youTube: ["youTube"],
  foreground2: ["foreground2"],
  valuePropsSection: ["valuePropsSection", "react", "vue", "svelte"],
  react: ["react"],
  vue: ["vue"],
  svelte: ["svelte"],
  banner: ["banner"],
  section: ["section", "foreground3"],
  foreground3: ["foreground3"],
  fathymFooter: ["fathymFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  foreground: "div";
  youTube: typeof YouTube;
  foreground2: "div";
  valuePropsSection: typeof Section;
  react: "a";
  vue: "a";
  svelte: "a";
  banner: typeof Banner;
  section: "section";
  foreground3: "div";
  fathymFooter: typeof FathymFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLandingPagesAngular2Test__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLandingPagesAngular2Test__VariantsArgs;
    args?: PlasmicLandingPagesAngular2Test__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLandingPagesAngular2Test__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLandingPagesAngular2Test__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLandingPagesAngular2Test__ArgProps,
          internalVariantPropNames:
            PlasmicLandingPagesAngular2Test__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicLandingPagesAngular2Test__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLandingPagesAngular2Test";
  } else {
    func.displayName = `PlasmicLandingPagesAngular2Test.${nodeName}`;
  }
  return func;
}

export const PlasmicLandingPagesAngular2Test = Object.assign(
  // Top-level PlasmicLandingPagesAngular2Test renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    foreground: makeNodeComponent("foreground"),
    youTube: makeNodeComponent("youTube"),
    foreground2: makeNodeComponent("foreground2"),
    valuePropsSection: makeNodeComponent("valuePropsSection"),
    react: makeNodeComponent("react"),
    vue: makeNodeComponent("vue"),
    svelte: makeNodeComponent("svelte"),
    banner: makeNodeComponent("banner"),
    section: makeNodeComponent("section"),
    foreground3: makeNodeComponent("foreground3"),
    fathymFooter: makeNodeComponent("fathymFooter"),

    // Metadata about props expected for PlasmicLandingPagesAngular2Test
    internalVariantProps: PlasmicLandingPagesAngular2Test__VariantProps,
    internalArgProps: PlasmicLandingPagesAngular2Test__ArgProps
  }
);

export default PlasmicLandingPagesAngular2Test;
/* prettier-ignore-end */
